# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildCfgVgcFull: 'full'
  v2rayCorePkgName: 'v2ray-windows-32.zip'
  v2rayCorePkgFolder: '$(Build.SourcesDirectory)/V2RayGCon/Resource/Pkg'
  v2rayCoreUrl: 'https://github.com/v2ray/dist/raw/master/$(v2rayCorePkgName)'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# V2RayGCon-full.zip
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildCfgVgcFull)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildCfgVgcFull)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/V2RayGCon/bin/$(buildCfgVgcFull)/'
    includeRootFolder: false
    archiveType: 'zip' # Options: zip, 7z, tar, wim
    #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
    archiveFile: '$(Build.ArtifactStagingDirectory)/V2RayGCon-$(buildCfgVgcFull).zip' 
    replaceExistingArchive: true 

# V2RayGCon-box.zip
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: import sys; print('Python version'); print(sys.version)

- task: PythonScript@0
  inputs:
    workingDirectory: '$(v2rayCorePkgFolder)'
    scriptSource: 'inline'
    script: from urllib import urlretrieve; import ssl; urlretrieve(url = '$(v2rayCoreUrl)', filename = '$(v2rayCoreFileName)', context = ssl._create_unverified_context())

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(v2rayCorePkgFolder)/$(v2rayCorePkgName)'
    destinationFolder: '$(Build.SourcesDirectory)/V2RayGCon/bin/$(buildCfgVgcFull)/core'
    cleanDestinationFolder: true

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Build.SourcesDirectory)/V2RayGCon/Resource/Pkg/vgctpl.zip'
    destinationFolder: '$(Build.SourcesDirectory)/V2RayGCon/bin/$(buildCfgVgcFull)/VGCTpl'
    cleanDestinationFolder: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/V2RayGCon/bin/$(buildCfgVgcFull)/'
    includeRootFolder: false
    archiveType: 'zip' # Options: zip, 7z, tar, wim
    #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
    archiveFile: '$(Build.ArtifactStagingDirectory)/V2RayGCon-box.zip' 
    replaceExistingArchive: true 

# md5.txt
- script: 'for %%a in (*.zip) do certutil -hashfile %%a MD5 >> md5.txt & echo. >> md5.txt'
  workingDirectory: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Calc md5 for releases.' 
  # failOnStderr: #
  # env:  # mapping of environment variables to add

- task: PublishBuildArtifacts@1
